version: '2'
services:
  bot:
    image: banjocat/tivix-brooklyn
    build: ./slackbot/.
    volumes:
      - "./slackbot/jsonstore:/bot/jsonstore"
      - "./slackbot//client_secret.json:/bot/client_secret.json"
      - "./slackbot/secrets.json:/bot/secrets.json"
      - ".credentials:/bot/.credentials"
    environment:
      ENV: ${ENV}
    depends_on:
      - mosca
  mosca:
    image: matteocollina/mosca
    ports:
      - "8000:80"
      - "1883:1883"
