version: '2'
services:
    bot:
        image: banjocat/tivix-brooklyn
        build: .
        volumes:
            - "./jsonstore:/bot/jsonstore"
        environment:
            BOT_TOKEN: ${BOT_TOKEN}
