version: 2
jobs:
  build:
    docker:
      - image: banjocat/fabric-alpine
    working_directory: ~/brooklyn
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "ce:1b:52:47:94:e7:f5:43:dc:a7:6e:ac:5d:3e:d2:6d"
      - setup_remote_docker:
          reusable: true
          exclusive: true
      - run: docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
      - run: fab build
      - deploy:
          name: Deploy Master
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              fab -i ${HOME}/.ssh/id_rsa_ce1b524794e7f543dca76eac5d3ed26d deploy
            fi

